<?php 

global $wpdb;
$table_prefix = $wpdb->prefix;

$sql_query = ["CREATE TABLE IF NOT EXISTS {$table_prefix}Student
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
StudentId INT(10) UNIQUE,
Name VARCHAR(100),
DateOfBirth VARCHAR(100),
Sex VARCHAR(10),
MobileNumber VARCHAR(15),
Address VARCHAR(255),
FatherName VARCHAR(100),
FatherMobileNumber VARCHAR(15)
)",

'CREATE TABLE IF NOT EXISTS User
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(255),
Password VARCHAR(255)
)',

'CREATE TABLE IF NOT EXISTS Area
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255)
)',

'CREATE TABLE IF NOT EXISTS Department
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(50)
)',

'CREATE TABLE IF NOT EXISTS Subject
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255),
Abbreviation VARCHAR(255),
IDArea INT references Area(ID)
)',

'CREATE TABLE IF NOT EXISTS Level(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255),
Principle VARCHAR(255)
)',

'CREATE TABLE IF NOT EXISTS Grade
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255),
IDLevel INT references Level(ID),
Observation VARCHAR(255)
)',


'CREATE TABLE IF NOT EXISTS Attendance
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IDStudent INT references Student(ID),
Attended VARCHAR(255),
Date VARCHAR(255)
)',

'CREATE TABLE IF NOT EXISTS SubjectGrade
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IDGrade INT references Grade(ID),
IDSubject INT references Subject(ID)
)',

'CREATE TABLE IF NOT EXISTS ScoreRecord
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
IDSubject INT references Subject(ID),
IDStudent INT references Student(ID),
FirstTrimester INT,
SecondTrimester INT,
ThirdTrimester INT,
FinalGrade INT,
Year VARCHAR(255)
)'];